POST http://localhost:3000/register/
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
  "name": "Adam Richard",
  "gender": "male"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username" : "JoeBiden",
    "password" : "biden@123",
}

###
GET http://localhost:3000/user/tweets/feed/
Authorization: Bearer 

###
GET http://localhost:3000/user/following/

###
GET http://localhost:3000/user/followers/
